name: basic-steps

on:
  workflow_call:

jobs:

  prepare-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble
        run: ./gradlew classes testClasses funTestClasses -s --parallel

  run-checks:
    needs: [prepare-env]
    runs-on: ubuntu-latest
    steps:
      - name: Assemble
        run: ./gradlew check -x test -x funTest -s --parallel

  run-unit-tests:
    needs: [prepare-env]
    runs-on: ubuntu-latest
    steps:
      - name: Unit Tests
        run: ./gradlew test -s --parallel

  run-functional-tests:
    needs: [prepare-env]
    runs-on: ubuntu-latest
    steps:
      - name: Functional Tests
        run: ./gradlew funTest -s --parallel

  post-build:
    needs: [run-checks, run-unit-tests, run-functional-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Build Coverage report
        run: ./gradlew jacocoRootReport

      - name: Upload JaCoCo coverage data
        uses: actions/upload-artifact@master
        with:
          name: tests-artifacts
          path: |
            */build/jacoco/**/*.exec
            */build/test-results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
